apiVersion: v1
kind: Service
metadata:
  name: text-to-sql-svc
  namespace: default
  labels:
    app: text-to-sql
spec:
  type: ClusterIP # Matches backend service type
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    app: text-to-sql